// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp634PTy3bUjvgSr999zzxKG_b3G4ytEY',
    appId: '1:573491167004:web:302b735cc1ac44f5c6c4d9',
    messagingSenderId: '573491167004',
    projectId: 'yookatale-b6513',
    authDomain: 'yookatale-b6513.firebaseapp.com',
    storageBucket: 'yookatale-b6513.appspot.com',
    measurementId: 'G-CNMTXGEQLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeOV7PSnt7YSKX1sjr8qXOPRe36s7fOc',
    appId: '1:573491167004:android:c2afba499437b599c6c4d9',
    messagingSenderId: '573491167004',
    projectId: 'yookatale-b6513',
    storageBucket: 'yookatale-b6513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JLVYHr7_ASPvvYIgCppOk0-lmsZ-_as',
    appId: '1:573491167004:ios:025507df8b423ea2c6c4d9',
    messagingSenderId: '573491167004',
    projectId: 'yookatale-b6513',
    storageBucket: 'yookatale-b6513.appspot.com',
    androidClientId: '573491167004-k56dlkm22m4nspc4o01bf0fbgqcimgs7.apps.googleusercontent.com',
    iosClientId: '573491167004-7gkhpdpte511fp328pf9tkg37ovko49j.apps.googleusercontent.com',
    iosBundleId: 'com.example.yookatale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JLVYHr7_ASPvvYIgCppOk0-lmsZ-_as',
    appId: '1:573491167004:ios:0aee28c42a526d90c6c4d9',
    messagingSenderId: '573491167004',
    projectId: 'yookatale-b6513',
    storageBucket: 'yookatale-b6513.appspot.com',
    androidClientId: '573491167004-k56dlkm22m4nspc4o01bf0fbgqcimgs7.apps.googleusercontent.com',
    iosClientId: '573491167004-e6u24em00c345gg56q6gmd70e13n71j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.yookatale.RunnerTests',
  );
}
