target 'Runner' do
    use_frameworks!
    use_modular_headers!
  
    # pod for screenshot prevention
    pod 'ScreenshotPreventing'
  
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end